language: node_js
node_js:
- lts/*
sudo: required
before_install:
- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn
install:
- yarn global add codecov
cache:
  yarn: true
  directories:
  - node_modules
script:
- cd ./broskichat-app
- yarn install
- CI=true yarn test
- cd ../broskichat-api
- yarn install
- yarn posttest
after_success:
- cd ../broskichat-app
- CI=true yarn coverage && codecov
notifications:
  slack: broskitownusa:DPJ68dsuWDAtrLTx1OyvgwVu
