codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

ignore:
  "src/registerServiceWorker.js" # Ignore the Default Service Worker
  "src/setupTests.js" # Ignore the testSetup config file
  "src/index.js" # Ignore the index file for webpack

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false